global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: kafka-exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - kafka-exporter:9308

  - job_name: jmx-exporter
    honor_timestamps: true
    scrape_interval: 145s
    scrape_timeout: 145s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - jmx-exporter:9404

  - job_name: kafka-connect-exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - kafka-connect-0:9405
          - kafka-connect-1:9405

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
