global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: kafka-source-exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - kafka-source-0:65000
          - kafka-source-1:65000
  - job_name: kafka-target-exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - kafka-target-0:65000
          - kafka-target-1:65000
  - job_name: kafka-connect-exporter
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - kafka-connect-0:65000
          - kafka-connect-1:65000

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
